-- AlterTable
ALTER TABLE `tags` MODIFY `tag1` VARCHAR(36) NULL,
    MODIFY `tag2` VARCHAR(36) NULL,
    MODIFY `tag3` VARCHAR(36) NULL,
    MODIFY `tag4` VARCHAR(36) NULL,
    MODIFY `tag5` VARCHAR(36) NULL;
